name: irrl5
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.13.0
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - cryptography=36.0.0
  - cudatoolkit=11.1.74
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - debugpy=1.5.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - ffmpeg=4.2.2
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2021.10.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.2
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.2
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libidn2=2.3.2
  - libnghttp2=1.46.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libzopfli=1.0.3
  - locket=0.2.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - munkres=1.1.4
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - networkx=2.6.3
  - notebook=6.4.6
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandocfilters=1.4.3
  - parso=0.8.3
  - partd=1.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.1.3
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyyaml=6.0
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.26.0
  - scikit-image=0.18.1
  - scipy=1.6.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlite=3.37.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tifffile=2021.7.2
  - tk=8.6.11
  - toolz=0.11.2
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - x264=1!157.20191217
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - antlr4-python3-runtime==4.8
    - cachetools==4.2.4
    - click==8.0.3
    - configparser==5.2.0
    - cython==0.29.26
    - decorator==4.4.2
    - dm-control==0.0.403778684
    - dm-env==1.5
    - dm-tree==0.1.6
    - docker-pycreds==0.4.0
    - easydict==1.9
    - fasteners==0.16.3
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.25
    - glfw==2.5.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - graphql-core==3.1.7
    - grpcio==1.43.0
    - h5py==3.6.0
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - imageio-ffmpeg==0.4.4
    - importlib-resources==5.4.0
    - ipdb==0.13.9
    - joblib==1.1.0
    - labmaze==1.0.5
    - lxml==4.7.1
    - markdown==3.3.6
    - matplotlib==3.5.0
    - moviepy==1.0.3
    - mujoco-py==2.1.2.14
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-python==4.5.3.56
    - pandas==1.3.0
    - pathtools==0.1.2
    - proglog==0.1.9
    - promise==2.3
    - protobuf==3.19.1
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyopengl==3.1.5
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-learn==1.0.2
    - seaborn==0.12.2
    - sentry-sdk==1.5.1
    - setuptools-scm==7.1.0
    - shortuuid==1.0.8
    - sklearn==0.0
    - smmap==5.0.0
    - submitit==1.4.1
    - tb-nightly==2.8.0a20220105
    - tensorboard-data-server==0.6.1
    - tensorboard-logger==0.1.0
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - threadpoolctl==3.0.0
    - toml==0.10.2
    - tomli==2.0.1
    - torchviz==0.0.2
    - tqdm==4.62.3
    - wandb==0.15.5
    - werkzeug==2.0.2
    - yapf==0.31.0